# Python Refresher

## Example with tuples

Tuples are immutable, faster and use less memory

In [1]:
empty_tuple = tuple()

In [2]:
empty_tuple

()

In [3]:
new_tuple = (1,'vanilla')

In [4]:
new_tuple

(1, 'vanilla')

In [5]:
new_tuple[1]

'vanilla'

In [6]:
new_tuple[1]='chocolate'      # tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [7]:
combined_tuple1 = empty_tuple + new_tuple

In [8]:
combined_tuple1

(1, 'vanilla')

In [9]:
combined_tuple2= new_tuple + (2,)    #this will not work with '(2)', as this is considered as integer

In [10]:
combined_tuple2

(1, 'vanilla', 2)

In [11]:
for i in range(len(combined_tuple2)):
    print(combined_tuple2[i])

1
vanilla
2


## Example with lists

Lists' elements can be modifed

In [12]:
my_list = list(combined_tuple2)

In [13]:
my_list

[1, 'vanilla', 2]

In [14]:
my_num = my_list.pop(2)

In [15]:
my_list

[1, 'vanilla']

In [16]:
my_list.insert(1,my_num)

In [17]:
my_list

[1, 2, 'vanilla']

In [18]:
my_list.append('honey')

In [19]:
my_list

[1, 2, 'vanilla', 'honey']

In [20]:
my_list[3] = 'chocolate'      # lists are mutable
my_list

[1, 2, 'vanilla', 'chocolate']

In [21]:
for i in range(len(my_list)):
    print(my_list[i])

1
2
vanilla
chocolate


In [22]:
my_ints = [i for i in my_list if isinstance(i,int)]
my_words = [i for i in my_list if isinstance(i,str)]

In [23]:
my_2d_list = [my_ints, my_words]

In [24]:
my_2d_list

[[1, 2], ['vanilla', 'chocolate']]

In [25]:
print(my_2d_list[0])

[1, 2]


In [26]:
print(my_2d_list[0][1])

2


In [27]:
print(my_2d_list[1])

['vanilla', 'chocolate']


In [28]:
print(my_2d_list[1][1])

chocolate


In [29]:
my_numbers, my_flavors = my_2d_list
print(my_numbers, my_flavors)

[1, 2] ['vanilla', 'chocolate']


In [30]:
for i, item in enumerate(my_2d_list):
    print(type(item), item)

<class 'list'> [1, 2]
<class 'list'> ['vanilla', 'chocolate']


In [31]:
for i, item in enumerate(my_2d_list):
    for i, item in enumerate(item):
        print(type(item), item)

<class 'int'> 1
<class 'int'> 2
<class 'str'> vanilla
<class 'str'> chocolate


## Example with dictionaries

Dictionaries are key-value pair data structures

In [32]:
my_dict = {}
for i in range(len(my_numbers)):
    my_dict[my_numbers[i]] = my_flavors[i] 

In [33]:
my_dict

{1: 'vanilla', 2: 'chocolate'}

In [34]:
my_dict[2]

'chocolate'

In [35]:
my_dict = dict(zip(my_numbers, my_words))
my_dict

{1: 'vanilla', 2: 'chocolate'}

In [36]:
my_dict[4] = 'coffee'
my_dict

{1: 'vanilla', 2: 'chocolate', 4: 'coffee'}

In [37]:
my_dict[3] = 'lemon'
my_dict

{1: 'vanilla', 2: 'chocolate', 4: 'coffee', 3: 'lemon'}

In [38]:
my_sorted_dict = dict(sorted(my_dict.items()))
my_sorted_dict

{1: 'vanilla', 2: 'chocolate', 3: 'lemon', 4: 'coffee'}

In [39]:
print(my_sorted_dict.keys())
print(my_sorted_dict.values())

dict_keys([1, 2, 3, 4])
dict_values(['vanilla', 'chocolate', 'lemon', 'coffee'])


In [40]:
my_sorted_dict[2]

'chocolate'

In [41]:
import json

print (json.dumps(my_sorted_dict, indent = 2, sort_keys = True))

{
  "1": "vanilla",
  "2": "chocolate",
  "3": "lemon",
  "4": "coffee"
}


In [42]:
jsonfile = open('mydict.json', 'w')
json.dump(my_sorted_dict, jsonfile, indent=4)
jsonfile.close()

In [43]:
import csv

with open('mydict.csv', 'w') as csvfile:    
    c = csv.writer(csvfile)
    for key, value in my_sorted_dict.items():
        c.writerow([key, value])

## Example with Numpy arrays

Best for using advanced math, but data types must be the same for all elements

In [44]:
from numpy import array

In [45]:
my_array = array(my_2d_list)
my_array    # but these will all be the same type: strings

array([['1', '2'],
       ['vanilla', 'chocolate']], dtype='<U21')

In [46]:
import numpy as np
another_array = np.array([0,10])
another_array

array([ 0, 10])

In [47]:
np.mean(my_array[0].astype(float))

1.5

In [48]:
np.random.randn(3) * 0.3 + 1      # 0.2 is std, 1 is mean of the standard distribution

array([0.93572654, 0.89037768, 1.70621542])

In [49]:
np.random.rand(5) *2 -1           # uniform random numbers from -1 to +1

array([-0.75343186, -0.10587094, -0.73178449, -0.44638058, -0.62614135])

In [50]:
my_array.shape

(2, 2)

In [51]:
np.shape(my_array)

(2, 2)

In [52]:
np.shape(my_2d_list)

(2, 2)

In [53]:
my_array=np.append(my_array,[[3],['coffee']], axis=1)
my_array

array([['1', '2', '3'],
       ['vanilla', 'chocolate', 'coffee']], dtype='<U21')

In [54]:
my_array=np.append(my_array,[['5 CHF', '5.5 CHF', '5.1 CHF']], axis=0)
my_array

array([['1', '2', '3'],
       ['vanilla', 'chocolate', 'coffee'],
       ['5 CHF', '5.5 CHF', '5.1 CHF']], dtype='<U21')

In [55]:
np.shape(my_array)

(3, 3)

In [56]:
print(my_array[0])
print(my_array[2])

['1' '2' '3']
['5 CHF' '5.5 CHF' '5.1 CHF']


In [57]:
print(my_array[:, 0])      # all rows, first column (vanilla)
print(my_array[:, 2])      # all rows, third column (coffee)

['1' 'vanilla' '5 CHF']
['3' 'coffee' '5.1 CHF']


In [58]:
print(my_array.T)

[['1' 'vanilla' '5 CHF']
 ['2' 'chocolate' '5.5 CHF']
 ['3' 'coffee' '5.1 CHF']]


In [59]:
product_dict = {}

for row in my_array.T:
    prodid = row[0]
    product_dict[prodid] = {
        'flavor': row[1],
        'price': row[2]
    }

In [60]:
product_dict

{'1': {'flavor': 'vanilla', 'price': '5 CHF'},
 '2': {'flavor': 'chocolate', 'price': '5.5 CHF'},
 '3': {'flavor': 'coffee', 'price': '5.1 CHF'}}

In [61]:
print (json.dumps(product_dict, indent = 2, sort_keys = True))

{
  "1": {
    "flavor": "vanilla",
    "price": "5 CHF"
  },
  "2": {
    "flavor": "chocolate",
    "price": "5.5 CHF"
  },
  "3": {
    "flavor": "coffee",
    "price": "5.1 CHF"
  }
}


### Exercise

Take prices as a list, add one element to have len=4, and add it to the dictionary *my_sorted_dict* (you may create a new dict as *new_product_dict*) 